// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCy7Sep9yErGFaefKuKmatFpp7xYjHCgoM',
    appId: '1:432806220789:web:0036478531394a140086bc',
    messagingSenderId: '432806220789',
    projectId: 'barber-860a1',
    authDomain: 'barber-860a1.firebaseapp.com',
    storageBucket: 'barber-860a1.appspot.com',
    measurementId: 'G-2SLT59NPC3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0u7xIvspe7f_2qIBo9i6QMumEYx6RxLg',
    appId: '1:432806220789:android:6cbc0a80551329830086bc',
    messagingSenderId: '432806220789',
    projectId: 'barber-860a1',
    storageBucket: 'barber-860a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHcbQlIGkk61yCyWdYDmdZWtdoV3eOuvg',
    appId: '1:432806220789:ios:0ef43826e84cc7e10086bc',
    messagingSenderId: '432806220789',
    projectId: 'barber-860a1',
    storageBucket: 'barber-860a1.appspot.com',
    iosBundleId: 'com.example.barberflutter1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHcbQlIGkk61yCyWdYDmdZWtdoV3eOuvg',
    appId: '1:432806220789:ios:2c4ca4b8bdc24cf20086bc',
    messagingSenderId: '432806220789',
    projectId: 'barber-860a1',
    storageBucket: 'barber-860a1.appspot.com',
    iosBundleId: 'com.example.barberflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCy7Sep9yErGFaefKuKmatFpp7xYjHCgoM',
    appId: '1:432806220789:web:68d71ef58989e4100086bc',
    messagingSenderId: '432806220789',
    projectId: 'barber-860a1',
    authDomain: 'barber-860a1.firebaseapp.com',
    storageBucket: 'barber-860a1.appspot.com',
    measurementId: 'G-BZD6KJJWKQ',
  );

}